apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: avi-integrations-php-runtime
  namespace: avin-development
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: tf.nonprd.avin.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: avi-integrations-php-runtime
            port:
              number: 8081
