apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: avi-integrations-php-runtime
  annotations:
     kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: tf.nonprd.avin.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: php-app-service
            port:
              number: 8080
