apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app-deployment
  namespace: avin-development
  labels:
    app: php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-app
        image: avinacr.azurecr.io/php-app:latest
        ports:
        - containerPort: 8081
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: php-app-service
spec:
  type: LoadBalancer
  selector:
    app: php-app
  ports:
  - protocol: TCP
    port: 8081
