apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
  namespace: avin-development
  labels:
    app: php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-app
        image: avinacr.azurecr.io/php-app:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-secret
