name: Deploy to Kubernetes

on:
  workflow_dispatch:
    inputs:
      k8s-deployment-file:
        description: 'Kubernetes Deployment file'
        required: true
        type: boolean
        default: false
      ingress-file:
        description: 'Kubernetes ingress file'
        required: true
        type: boolean
        default: false
      service-file:
        description: 'Kubernetes service file'
        required: true
        type: boolean
        default: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: '{
          "clientId": "36ffaa78-8a23-4b13-a58f-dbf35e74818f",
          "clientSecret": "17QGWRm2BXjqmL2mgeqVqXT-z7_DS5~sTo",
          "subscriptionId": "267792e5-47b0-4a0f-ab38-666ea8d90ed7",
          "tenantId": "6315fddc-01d3-43ed-a687-195101704294"
        }'

    - name: Set up AKS credentials
      run: az aks get-credentials --resource-group avin-tf-rg --name avin-tf-aks
     
    - name: Define Service
      if: ${{ github.event.inputs.service-file }}
       run: kubectl apply -f app-service.yml

    - name: Define Ingress
      if: ${{ github.event.inputs.ingress-file }}
       run: kubectl apply -f ingress.yml
      
    - name: Deploy to Kubernetes
      if: ${{ github.event.inputs.k8s-deployment-file }}
      run: kubectl apply -f k8s-deployment.yml
