name: 'Terraform Deployment'

on:
  push:
    branches: [ "main" ]
  pull_request:
    
permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Set up environment variables
      run: |
        echo "AZURE_CLIENT_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}" >> $GITHUB_ENV
        echo "AZURE_CLIENT_SECRET=${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}" >> $GITHUB_ENV
        echo "AZURE_SUBSCRIPTION_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}" >> $GITHUB_ENV
        echo "AZURE_TENANT_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}" >> $GITHUB_ENV
    - name: Terraform Init
      run: terraform init -input=false

    - name: Terraform Format
      run: terraform fmt

    - name: Terraform Validate 
      run: terraform validate -no-color

    - name: Terraform plan
      run: terraform plan -input=false -no-color

    - name: Apply Terraform
      id: apply
      continue-on-error: true
      run: terraform apply -input=false -no-color -auto-approve

    - name: Destroy Terraform
      continue-on-error: true
      run: terraform apply -input=false -no-color -auto-approve
